[package]
name = "teranex-ctl"
version = "0.1.0"
authors = ["Guillaume Desmottes <guillaume.desmottes@collabora.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
failure = "0.1"
log = "0.4"
env_logger = "0.6"
